baseURL: "https://boonepeter.github.io/"
title: Peter Boone
paginate: 8
theme: hugo-PaperMod
enableInlineShortcodes: true
enableRobotsTXT: true

googleAnalytics: UA-125699184-1

minify:
  disableXML: true
  minifyOutput: true

languages:
  en:
    languageName: "English"
    weight: 1
    menu:
      main:
        - name: Archives
          url: /archive/
          weight: 5
        - name: Tags
          url: /tags/
          weight: 10
        - name: Subscribe
          url: https://buttondown.email/boonepeter
          weight: 11

params:
  env: production
  description: "A blog about choroideremia and tech"
  author: Peter Boone
  ShowReadingTime: true
  defaultTheme: auto
  ShowShareButtons: false
  displayFullLangName: true
  # images: ""
  # assets:
  #   favicon: '<path / external url>'

  #profileMode:
    #enabled: false
    #title: PaperMod
    #imageUrl: "#"
    #imageTitle: my image
    # imageWidth: 120
    # imageHeight: 120
    #buttons:
    #  - name: Archives
    #    url: archives
    #  - name: Tags
    #    url: tags

  homeInfoParams:
    Title: "Welcome!"
    Content: >
      I'm Peter, a software engineer with a background in molecular biology. 

      > 
      
      I write about [choroideremia](https://en.wikipedia.org/wiki/Choroideremia) (an eye disease I have) and tech on this blog.

      >       
  socialIcons:
    - name: github
      url: "https://github.com/boonepeter"
    - name: linkedin
      url: "https://www.linkedin.com/in/boonepeter"
    - name: stackoverflow
      url: "https://stackoverflow.com/users/10703868/peter-boone"
  
  subscribe: "https://buttondown.email/boonepeter"

taxonomies:
  tag: tags

privacy:
  vimeo:
    disabled: true
    simple: true

  twitter:
    disabled: true
    enableDNT: true
    simple: true

  instagram:
    disabled: true
    simple: true

  youtube:
    disabled: true
    privacyEnhanced: true

services:
  instagram:
    disableInlineCSS: true
  twitter:
    disableInlineCSS: true
